name: Deploy to edwinjr.com

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Sync Files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /home/edwinjrc31/domains/edwinjr.com/public_html/
          port: 21
          protocol: ftps